name: flutter_application_1
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.2.6
  hexcolor: ^2.0.7
  dotted_border: ^2.0.0+2
  google_fonts: ^2.1.0
  provider:
  floor:
  intl:

dev_dependencies:
  build_runner:
  floor_generator:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0

  flutter_native_splash: ^2.2.6

flutter_native_splash:
  color : "22AA56"
  image : "assets/images/Gest.png"
  

flutter:
  assets :
    - assets/images/
  uses-material-design: true

